version: "3.9"

services:
  bot:
    build: .
    image: bot:${TAG}
    container_name: bot
    network_mode: host # name of your network
    pull_policy: never
    environment:
     - TOKEN
     - BOT_NAME
     - API_HASH
     - API_ID
     - SUPPORT_CHAT
     - REDIS_URL
  
networks:
  default: 
    external: true
    name: host